version: '3'


services:
  backend:
    container_name: backend
    restart: always
    # Overwrite some env variables
    environment:
      - HOST=covidframework.com
      - NODE_ENV=production
      - ATLAS_URI_MONGO=mongodb+srv://admin:RRTGwiGAwoSzem8K@covidcluster.spwpg.mongodb.net/CovidFramework?retryWrites=true&w=majority
    volumes:
       - covid-volume:/usr/share/covid-volume
    image: "ghcr.io/pako332/covid-framework/server:latest"
    ports:
      - "3000:3000"
    networks:
      - covid-network
  frontend:
    restart: always
    container_name: frontend
    # Overwrite some env variables
    environment:
      - REACT_APP_API_URL=covidframework.com
      - NODE_ENV=production
      - ATLAS_URI_MONGO=mongodb+srv://admin:RRTGwiGAwoSzem8K@covidcluster.spwpg.mongodb.net/CovidFramework?retryWrites=true&w=majority
    volumes:
       - covid-volume:/usr/share/covid-volume
    image: "ghcr.io/pako332/covid-framework/app:latest"
    ports:
      - "443:443"
    networks:
      - covid-network
    depends_on:
      - backend

volumes:
  covid-volume:
    external: true

networks:
   covid-network:
        driver: bridge
