version: '3'
volumes:
  covid-volume:
    external: true
services:
  backend:
    container_name: backend
    restart: always
    # Overwrite some env variables
    environment:
      - HOST=covidframework.com
      - NODE_ENV=production
    volumes:
       - covid-volume:/usr/share/covid-volume
    image: "ghcr.io/pako332/covid-framework/server:latest"
    ports:
      - "3000:3000"
    networks:
      - webappnetwork
  frontend:
    restart: always
    container_name: frontend
    # Overwrite some env variables
    environment:
      - REACT_APP_API_URL=covidframework.com
      - NODE_ENV=production
    volumes:
       - covid-volume:/usr/share/covid-volume
    image: "ghcr.io/pako332/covid-framework/app:latest"
    ports:
      - "443:443"
    networks:
      - webappnetwork
    depends_on:
      - backend
networks:
   webappnetwork:
        driver: bridge
