version: '3'

services:

  backend:
    container_name: backend
    restart: always
    image: "ghcr.io/pako332/covid-framework/server-local:latest"
    ports:
      - "3000:3000"
    networks:
      - covid-network

  frontend:
    restart: always
    container_name: frontend
    image: "ghcr.io/pako332/covid-framework/app-local:latest"
    ports:
      - "443:443"
    networks:
      - covid-network
    depends_on:
      - backend
  grafana:
    restart: always
    container_name: grafana
    environment:
      - GF_INSTALL_PLUGINS=grafana-worldmap-panel
      - GF_SERVER_HTTP_PORT=5000
    image: "grafana/grafana"
    ports:
      - 5000:5000
    networks:
      - covid-network
    

volumes:
  covid-volume:

networks:
   covid-network:
        driver: bridge
